### ISSUE TITLE
The ARM templates does not deploy the latest Edge runtime

### ISSUE THREAD

**Issue by rido-min** [Azure/iotedge-vm-deploy#1]
Creating a VM using the `Azure IoT Edge on Ubuntu`  ARM template

Observed. The `iotedge` version deployed is `iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)` on Ubuntu 16

Expected. The latest iotedge runtime, as per today it's  https://github.com/Azure/azure-iotedge/releases/tag/1.1.0  targeting the latest supported Ubuntu 18

**Comment by veyalla** [comment]
Cannot repro. Which docs are you following?

**Comment by rido-min** [comment]
I found it in the marketplace, as explained https://azure.microsoft.com/en-us/blog/azure-iot-edge-runtime-available-for-ubuntu-virtual-machines/

But seems it has been removed, so closing this issue.
