### ISSUE TITLE
Deployment failed with validation error

### ISSUE THREAD

**Issue by alanrenmsft** [Azure/iotedge-vm-deploy#8]
following the example here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-ubuntuvm
and I am getting this error:
{"error":{"code":"InvalidTemplate","message":"Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'Boolean'. Actual 'String'. Please see https://aka.ms/resource-manager-parameter-files for usage details.'.","additionalInfo":[{"type":"TemplateViolation","info":{"lineNumber":54,"linePosition":17,"path":"parameters.allowSsh"}}]}

this used to work a month or so ago last time I checked.

**Comment by kgremban** [comment]
This issue should be resolved with the merging of the following PR: https://github.com/Azure/iotedge-vm-deploy/pull/7. Please let us know if you're still getting that error.

**Comment by alanrenmsft** [comment]
yes, it is working now, thanks for the quick fix.
